name: Publish new nextcloud-plus image

on:
  push:
    paths:
    - 'nextcloud/**'
    - '.github/workflows/nextcloud-plus.yml'
    branches:
    - main

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:nextcloud'
          push: true
          tags: freaktechnik/nextcloud-plus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
